### ISSUE TITLE
NoSuchMethodError: Guava and JIRA REST Client

### ISSUE THREAD

**Issue by lars-sh** [Hapag-Lloyd/oversigt#46]
On error we featured the below stacktrace. The JIRA REST Client which we are using is based on Guava 18 while we're using Guava 28.

It seems Atlassian offers an even more up-to-date version at https://bitbucket.org/atlassian/jira-rest-java-client - sadly not via Maven repository. That one might either be published, forked or such.

```
java.util.concurrent.ExecutionException: com.atlassian.httpclient.api.ResponseTransformationException: java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.atlassian.util.concurrent.Promises$OfStage.get(Promises.java:353)
	at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.get(DelegatingPromise.java:101)
	at com.hlag.oversigt.connect.jira.UnlimitedJiraClient.search(UnlimitedJiraClient.java:75)
	at com.hlag.oversigt.connect.jira.ThreadedJiraClient.lambda$search$0(ThreadedJiraClient.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hlag.oversigt.util.GrowingExecutor.executeTasks(GrowingExecutor.java:294)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.atlassian.httpclient.api.ResponseTransformationException: java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
	at com.atlassian.httpclient.api.DefaultResponseTransformation$DefaultResponseTransformationBuilder.lambda$defaultThrowableHandler$1(DefaultResponseTransformation.java:202)
	at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:334)
	at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:422)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doCompleted$0(SettableFuturePromiseHttpPromiseAsyncClient.java:37)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
	at com.atlassian.jira.rest.client.api.domain.util.ErrorCollection.toString(ErrorCollection.java:69)
	at com.google.common.collect.SingletonImmutableList.toString(SingletonImmutableList.java:70)
	at com.atlassian.jira.rest.client.api.RestClientException.<init>(RestClientException.java:62)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:176)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:170)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:49)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:10)
	at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:332)
	... 11 more
```

**Comment by noxone** [comment]
Has been fixed by using Guava 20.0
